// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYYikOpBk1iT8Y9pQpZp_ThZpoih5aF5M',
    appId: '1:374546709823:web:e2dce965bb3c9e4c44e78a',
    messagingSenderId: '374546709823',
    projectId: 'appdevfinalterm',
    authDomain: 'appdevfinalterm.firebaseapp.com',
    storageBucket: 'appdevfinalterm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1vEoyxZhjEXPROo9hlLVvOdih2KM7FwI',
    appId: '1:374546709823:android:f52ceadfd683169f44e78a',
    messagingSenderId: '374546709823',
    projectId: 'appdevfinalterm',
    storageBucket: 'appdevfinalterm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATeaLKZ5IIaO1kyz4Zu1LTs10gD8fIR4k',
    appId: '1:374546709823:ios:9b8c4e79e20d7a0e44e78a',
    messagingSenderId: '374546709823',
    projectId: 'appdevfinalterm',
    storageBucket: 'appdevfinalterm.appspot.com',
    iosClientId: '374546709823-8142jn4dqk14c44nf6p3voa4lmth7av3.apps.googleusercontent.com',
    iosBundleId: 'com.example.finaltermProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATeaLKZ5IIaO1kyz4Zu1LTs10gD8fIR4k',
    appId: '1:374546709823:ios:ad50a6da53c7c25344e78a',
    messagingSenderId: '374546709823',
    projectId: 'appdevfinalterm',
    storageBucket: 'appdevfinalterm.appspot.com',
    iosClientId: '374546709823-i5hulga4sh3564bdputkicsracnhccjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.finaltermProject.RunnerTests',
  );
}
